# Generated by Django 2.0.13 on 2019-08-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_password',
        ),
    ]
