# Generated by Django 2.0.13 on 2019-08-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_auto_20190814_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
