# Generated by Django 2.0.13 on 2019-08-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0005_auto_20190815_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='list_title',
        ),
        migrations.RemoveField(
            model_name='list',
            name='card_title',
        ),
    ]
